version: '3.9'
services:
  xui:
    image: enwaiax/x-ui
    container_name: x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    restart: unless-stopped
    ports:
      - 80:80
      - 54321:54321