services:
  xui:
    image: enwaiax/x-ui
    restart: unless-stopped
    container_name: x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/


  web:
    image: war7ng/go-web:v2-20230520-094035
    restart: unless-stopped
    env_file:
      - ./.env
 
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./cert:/root/cert:ro
      - ./nginx/logs:/var/log/nginx:rw
    ports:
      - 80:80
      - 54321:54321
      - 8081:8081
